"use client";

import type { Metadata } from "next";
import "./globals.css";
import { useEffect } from "react";
import { useAuthStore } from "../store/auth/auth-store";
import Toastify from "../components/common/toast/toast";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = useAuthStore();

  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Toastify />

        {children}
      </body>
    </html>
  );
}
